
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rmvilfesooqkvjbwvnrh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJtdmlsZmVzb29xa3ZqYnd2bnJoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0OTYzODMsImV4cCI6MjA2MTA3MjM4M30.NVol5ZvczKeb0XFOb5k17OHdQikSAzEFBzN1p01W2UQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
